### ISSUE TITLE
Timing of 3D image reconstruction

### ISSUE THREAD

**Issue by zhenghh04** [jtschwar/tomo_TV#4]
Hi Jonathan, 

I am Huihuo, working with Yi to optimize your code to run on ALCF machine. 

I quickly checked the timing of 
This is the timing of 3D/ASD_tv.py.
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/5777773/59132337-8f7db700-893a-11e9-98ee-335d0482576f.png">

In the current implementation TV minimization took majority of the time. We suggest to use C++ code for the TV part. 

The other issue is the definition of recon. It was defined as, 
recon = np.zeros([Nslice, Nray, Nray], dtype=np.float32)
should it be recon = np.zeros([Nray, Nray, Nslice], dtype=np.float32) instead? 

Huihuo

**Comment by jtschwar** [comment]
Hi @zhenghh04, 

Please to meet you. It's not surprising that the python implementation for TV part is slowing us down. I'll write it in C++ this week. 

The library I'm using to read tif stacks (skimage.io.imread) seems to import the dimensions for the stacks as (z,y,x) where z is the number of projections and x/y are the number of pixels in the respective directions.
I've pushed a commits over this weekend so now the dimensions are (x,y,z) by swapping 0 and 2nd axis.

**Comment by jtschwar** [comment]
@zhenghh04 
Hi Huihuo, thank you for providing your C++ implementation of tv-minimization. It has been extremely helpful.
I've spent the past week restructuring the 3D code to get significant speed up. If possible, would you mind taking one last look at it? I'm not too familiar with OpenMP so I wonder if there's a more efficient way to parallelize the for loops than the way I did... 
Thanks. Best, 
Jonathan
